version: '3.8'

services:
  tradestatengine:
    build: .
    container_name: tradestatengine
    ports:
      - "5000:5000"
      - "5050:5050"
      - "8050:8050"
    volumes:
      - tradestatengine_data:/app/app/data
    restart: always

volumes:
  tradestatengine_data:
    driver: local
